### PR TITLE
hunter package manager support

### PR DESCRIPTION
**Pull request by nimetu**
This adds support to [Hunter package manager](https://github.com/cpp-pm/hunter) to compile needed static external libraries.

Does not quite work with QT apps yet.

This should probably also bump cmake version to 3.16 (version I used under linux) as some packages (png, zlib I think) fail.

macOS not tested.

Use cmake option -DHUNTER_ENABLED=ON to enable hunter build

### CODE REVIEW

**Comment by kaetemi** [comment]
Neat. Is your luabind fork much different from this one https://github.com/Oberon00/luabind?

**Comment by nimetu** [comment]
> Neat. Is your luabind fork much different from this one https://github.com/Oberon00/luabind?

My fork is older. Its from Kervala hq repo, so I think its same as used in live.

**Comment by nimetu** [comment]
I updated this to use core4 branch and are using ValyriaTear/luabind now.

**Comment by kaetemi** [comment]
Could you add a build script in azure-pipelines.yml to auto-build it under Windows with Hunter?

**Comment by nimetu** [comment]
I think gitlab-github sync force pushed over my changes.

**Comment by kaetemi** [comment]
Yikes, that gitlab sync is aggressive...

**Comment by kaetemi** [comment]
@ulukyn Can you please update your mirror settings to **enable** "Overwrite diverged branches" on pulling?

**Comment by ulukyn** [comment]
@kaetemi the current option are :

image

Keep divergent refs must be checked so?

**Comment by kaetemi** [comment]
Hm, no, that's the push option. That should remain off, otherwise the mirror will diverge. Is the pull option not visible?

**Comment by ulukyn** [comment]
Ok i have removed and created a new pull mirror and see the options. It's enabled now

**Comment by kaetemi** [comment]
Alright. Let's see if that works right. :)

**Comment by nimetu** [comment]
win2019 works fine(ish). I hope caching hunter cache folder works as compiling all the packages (openssl/luabind are slow to compile) takes about 40min otherwise.

**Comment by nimetu** [comment]
Direct3D / XAudio2 drivers need some work until they compile from DirectX from Win10 SDK. I think nuget has a package with missing files and might be possible to use that.

**Comment by kaetemi** [comment]
Apparently it might be possible to just download https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe and extract it with 7zip to C:\\.

Let's try this 6525990b849ac4d0a12081cfcb5e624f9d5c40b4 c509410743460fee82ca44283cfb28b764f660f2 ...

**Comment by kaetemi** [comment]
I think it needs the whole c:/.hunter/_Base folder cached. It appears to be rebuilding still.

**Comment by nimetu** [comment]
I tried caching entire hunter folder, but next run failed to unpack it because of hard links error.

```
2021-11-24T19:16:09.7257064Z -- [hunter] HUNTER_ROOT: C:/.hunter
2021-11-24T19:16:09.7258382Z -- [hunter] [ Hunter-ID: fbdd94b | Toolchain-ID: c7d9676 | Config-ID: caac3d7 ]
2021-11-24T19:16:10.0886336Z -- [hunter] ZLIB_ROOT: C:/.hunter/_Base/fbdd94b/c7d9676/caac3d7/Install (ver.: 1.2.11-p1)
2021-11-24T19:16:10.1093602Z -- [hunter] Cache HIT: ZLIB
2021-11-24T19:16:10.1094495Z -- [hunter] Cache info: C:/.hunter/_Base/Cache/meta/c7d9676/ZLIB/1.2.11-p1/fbb8be7/da39a3e/a23c16c/e5fa44f/da39a3e/cache.sha1
```

I have this in the pipeline build log on second run. cmake task took less than 3min that time.
cache is also per branch (I see you added dxsdk with different branch).

**Comment by kaetemi** [comment]
Ah, you're right. It's because of the branch.

**Comment by kaetemi** [comment]
Looks good, then.

**Comment by kaetemi** [comment]
Does this work on Linux as well, or is this Windows-only?

Supporting the Qt tools doesn't seem like a requirement, right now. They haven't been maintained properly.

**Comment by nimetu** [comment]
It will work on linux/windows/macOS. I will add them.

macOS currently has issues (probably Xcode 13 related) and hunter insists compiling both debug and release packages.

**Comment by nimetu** [comment]
ubuntu18 and macOS versions for hunter added.
Changing to ubuntu20 is just a vmImage change,  I used 18 because that I can actually run, ubuntu20 uses newer glibc so it does not work on my (ubuntu 18) home linux.

**Pull request merged**
